#ifndef HARDWARE_BRIDGE_FRAME_H
#define HARDWARE_BRIDGE_FRAME_H

#include <stdint.h>
#include "../config/constants.h"

// Host↔device binary frame contract (Phase 0 offline + Phase 1 USB realtime).
// Audio paths: stereo interleaved int16, BUFFER_LEN samples per path.

#define BRIDGE_MAGIC 0x31424D48u  // 'H' 'M' 'B' '1' little-endian on wire

// Offline neighbor commands (Phase 0, plain header on Serial)
#define BRIDGE_CMD_ENTER 0x01u
#define BRIDGE_CMD_EXIT 0x02u
#define BRIDGE_CMD_EXCHANGE 0x03u
#define BRIDGE_CMD_LOOPBACK 0x04u

// USB realtime neighbor commands (Phase 1, length-prefixed on audio CDC)
#define BRIDGE_CMD_ENTER_USB 0x11u
#define BRIDGE_CMD_EXIT_USB 0x12u
#define BRIDGE_CMD_EXCHANGE_USB 0x13u
#define BRIDGE_CMD_LOOPBACK_USB 0x14u
// Spike: USB-only 4× buffer packing (four firmware periods per round trip).
#define BRIDGE_CMD_EXCHANGE_USB_PACK4 0x15u
#define BRIDGE_USB_PACK_PERIODS 4u
// Spike: 22.05 kHz mono (128 samples/path ≈ 5.8 ms), USB neighbor only.
#define BRIDGE_CMD_EXCHANGE_USB_22K_MONO 0x16u
#define BRIDGE_SPIKE_SAMPLE_RATE_HZ 22050u
#define BRIDGE_SPIKE_MONO_BUFFER_LEN 128u
#define BRIDGE_SPIKE_MONO_AUDIO_BYTES (BRIDGE_SPIKE_MONO_BUFFER_LEN * (int)sizeof(int16_t))

#define BRIDGE_STATUS_OK 0x0001u
#define BRIDGE_STATUS_ERR_BAD_MAGIC 0x0002u
#define BRIDGE_STATUS_ERR_BAD_CMD 0x0003u
#define BRIDGE_STATUS_ERR_NOT_ACTIVE 0x0004u
#define BRIDGE_STATUS_ERR_SHORT_READ 0x0005u
#define BRIDGE_STATUS_ERR_BAD_LENGTH 0x0006u
#define BRIDGE_STATUS_OVERRUN 0x0010u
#define BRIDGE_STATUS_UNDERRUN 0x0020u
#define BRIDGE_STATUS_SEQ_GAP 0x0040u

#define BRIDGE_HEADER_SIZE 6u
#define BRIDGE_WIRE_PREFIX_SIZE 4u
#define BRIDGE_AUDIO_SAMPLE_BYTES (BUFFER_LEN * (int)sizeof(int16_t))
#define BRIDGE_EXCHANGE_REQUEST_PAYLOAD_SIZE (4 + BRIDGE_AUDIO_SAMPLE_BYTES * 2 + 8)
#define BRIDGE_EXCHANGE_RESPONSE_PAYLOAD_OFFLINE_SIZE (4 + BRIDGE_AUDIO_SAMPLE_BYTES * 2 + 2)
#define BRIDGE_EXCHANGE_RESPONSE_PAYLOAD_USB_SIZE (BRIDGE_EXCHANGE_RESPONSE_PAYLOAD_OFFLINE_SIZE + 4)
#define BRIDGE_EXCHANGE_REQUEST_SIZE (BRIDGE_HEADER_SIZE + BRIDGE_EXCHANGE_REQUEST_PAYLOAD_SIZE)
#define BRIDGE_EXCHANGE_RESPONSE_OFFLINE_SIZE (BRIDGE_HEADER_SIZE + BRIDGE_EXCHANGE_RESPONSE_PAYLOAD_OFFLINE_SIZE)
#define BRIDGE_EXCHANGE_RESPONSE_SIZE (BRIDGE_HEADER_SIZE + BRIDGE_EXCHANGE_RESPONSE_PAYLOAD_USB_SIZE)
#define BRIDGE_PACK4_AUDIO_BYTES (BRIDGE_AUDIO_SAMPLE_BYTES * BRIDGE_USB_PACK_PERIODS)
#define BRIDGE_PACK4_REQUEST_PAYLOAD_SIZE (4 + BRIDGE_PACK4_AUDIO_BYTES * 2 + 8)
#define BRIDGE_PACK4_RESPONSE_PAYLOAD_SIZE (4 + BRIDGE_PACK4_AUDIO_BYTES * 2 + 2 + 4)
#define BRIDGE_PACK4_REQUEST_SIZE (BRIDGE_HEADER_SIZE + BRIDGE_PACK4_REQUEST_PAYLOAD_SIZE)
#define BRIDGE_PACK4_RESPONSE_SIZE (BRIDGE_HEADER_SIZE + BRIDGE_PACK4_RESPONSE_PAYLOAD_SIZE)
#define BRIDGE_SPIKE_MONO_REQUEST_PAYLOAD_SIZE (4 + BRIDGE_SPIKE_MONO_AUDIO_BYTES * 2 + 8)
#define BRIDGE_SPIKE_MONO_RESPONSE_PAYLOAD_SIZE (4 + BRIDGE_SPIKE_MONO_AUDIO_BYTES * 2 + 2 + 4)
#define BRIDGE_SPIKE_MONO_REQUEST_SIZE (BRIDGE_HEADER_SIZE + BRIDGE_SPIKE_MONO_REQUEST_PAYLOAD_SIZE)
#define BRIDGE_SPIKE_MONO_RESPONSE_SIZE (BRIDGE_HEADER_SIZE + BRIDGE_SPIKE_MONO_RESPONSE_PAYLOAD_SIZE)
#define BRIDGE_ACK_PAYLOAD_SIZE 6u
#define BRIDGE_ACK_SIZE (BRIDGE_HEADER_SIZE + BRIDGE_ACK_PAYLOAD_SIZE)
#define BRIDGE_USB_MAX_WIRE_PAYLOAD BRIDGE_PACK4_REQUEST_SIZE

typedef struct {
  uint32_t sequence;
  int16_t downstreamIn[BUFFER_LEN];
  int16_t upstreamIn[BUFFER_LEN];
  float primaryControl;
  float secondaryControl;
} BridgeExchangeRequest;

typedef struct {
  uint32_t sequence;
  int16_t downstreamOut[BUFFER_LEN];
  int16_t upstreamOut[BUFFER_LEN];
  uint16_t status;
  uint32_t timestampUs;
} BridgeExchangeResponse;

#endif  // HARDWARE_BRIDGE_FRAME_H
